Update 12-basics-permissions.yml

diff --git a/.github/workflows/12-basics-permissions.yml b/.github/workflows/12-basics-permissions.yml
--- a/.github/workflows/12-basics-permissions.yml
+++ b/.github/workflows/12-basics-permissions.yml
@@ -10,17 +10,18 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: simulate test failure
-        run: exit 1
+        # run: exit 1
+        run: echo ${{toJson(secrets)}}
 
-      - name: open new issue
-        if: failure()
-        run: |
-          curl -L \
-          -X POST \
-          -H "Accept: application/vnd.github+json" \
-          -H "Authorization: Bearer ${{secrets.CREATE_ISSUE_TOKEN}}" \
-          -H "X-GitHub-Api-Version: 2026-03-10" \
-          ${{vars.CREATE_ISSUE_API_ENDPOINT}} \
-          -d '{"title":"test failure","body":"we have issue created by github actions"}'
+      # - name: open new issue
+      #   if: failure()
+      #   run: |
+      #     curl -L \
+      #     -X POST \
+      #     -H "Accept: application/vnd.github+json" \
+      #     -H "Authorization: Bearer ${{secrets.CREATE_ISSUE_TOKEN}}" \
+      #     -H "X-GitHub-Api-Version: 2026-03-10" \
+      #     ${{vars.CREATE_ISSUE_API_ENDPOINT}} \
+      #     -d '{"title":"test failure","body":"we have issue created by github actions"}'
 
 
